# appspec.yml
version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/fork-server
    overwrite: yes
permissions:
  - object: /home/ubuntu/fork-server
    owner: ubuntu
    group: ubuntu
    mode: 755
hooks:
  AfterInstall:
    - location: deploy.sh
      timeout: 60
      runas: root