package com.titanic.fork.utils;

import lombok.Getter;

@Getter
public enum LocalTestEnum {
    JWT_TOKEN_LOCAL_TEST_1("eyJIUzI1NiI6IkhTMjU2IiwidHlwIjoiSldUIiwiYWxnIjoiSFMyNTYifQ.eyJBdXRob3JpemF0aW9uIjoiZ3Vzd25zMTY1M0BnbWFpbC5jb20iLCJzdWIiOiJndXN3bnMxNjUzQGdtYWlsLmNvbSIsImV4cCI6MTYwMTYzODI4OCwiaWF0IjoxNjAwNzc0Mjg4fQ.A6dxOdl0HnHqogXln8imccrZJ_WxVdYKbE9f728duXg"),
    JWT_TOKEN_LOCAL_TEST_2("eyJIUzI1NiI6IkhTMjU2IiwidHlwIjoiSldUIiwiYWxnIjoiSFMyNTYifQ.eyJBdXRob3JpemF0aW9uIjoiZ3Vzd25zMTY1M0BnbWFpbC5jb20iLCJzdWIiOiJndXN3bnMxNjUzQGdtYWlsLmNvbSIsImV4cCI6MTYwMTYzODI4OCwiaWF0IjoxNjAwNzc0Mjg4fQ.A6dxOdl0HnHqogXln8imccrZJ_WxVdYKbE9f728duXg"),
    JWT_TOKEN_LOCAL_TEST_3("eyJIUzI1NiI6IkhTMjU2IiwidHlwIjoiSldUIiwiYWxnIjoiSFMyNTYifQ.eyJBdXRob3JpemF0aW9uIjoiZ3Vzd25zMTY1M0BnbWFpbC5jb20iLCJzdWIiOiJndXN3bnMxNjUzQGdtYWlsLmNvbSIsImV4cCI6MTYwMTYzODI4OCwiaWF0IjoxNjAwNzc0Mjg4fQ.A6dxOdl0HnHqogXln8imccrZJ_WxVdYKbE9f728duXg");

    private String value;

    LocalTestEnum(String value) {
        this.value = value;
    }
}
